travis:
  secure:
    BINSTAR_TOKEN: Uyg0OQCpST//0LUFriMgQZOpLI9xzffQvSpvsqJSJ+nuntRQGP8lGFybnQpqwIQCylhccNeMM37qv1AYW5fYTkAMI8rZcd/O+2Ej1ZFno32Aa6vWwMNLw/Hihd/DSdYtl5SLdSU9DdIDlWNwBCfhB2ER6lATYIQGtCUmxSeFlKeGpZm2HPUn9bKjXh3EdD+t6+zKnqn+e1UQGVJYl9HX6W0dObcpxflKEpsoLgtDqMxwFOIHEdjNJwLJJb7fV5FUJVuMBDaH6Kee/eKQKKNc7ZabZEXKO5SNtKHI6BKML9w7+DIS1cER0Jh7xuBwiakyvMWJXp1NrbKWyAqh8rxh1qCvE8BV0XRpBlKW3HJeGKCtxi12ooMkSAdxipzjaj1c2SlrQ3ZVaXlZeYMpk1iXBUlPLc2UK4d/uEHRqNIrdPPDRFqLYeRgdWF9EhCo82V0LXH1XfhUnirpya24XVZEbQiDwNyvI52F6/83FbhnBnRF1ysdXLZvy6h8Kv5zWC/vecS/04LuLy6iEX5ns+7fKbyNM3zwSB6VJWjHRa3hRyKS7JxyYh+IAOj/AGrjur0MiU6eC+XJIemxKzzkinAHEIUsx0ylrdQTxEa00cLqmgTsZRzrSlPuzzPoGehvbM6ZlGgRMHNTWd1xpT1A9TDkOaC0UDSSy52OknfXqtu+Njw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
