travis:
  secure:
    BINSTAR_TOKEN: jWqN3IZ++txnwcrcCcELpNvtrrw5HkKRlm4tpch+zkBzQFYx0/r1Eo2cKF2nx7A3zIU7FEZlkJe2URxaPTAAu9PPsc+kcko7W0W2hFXvvPgSfWj7RfO/nplFjxwSvbAc+yY/TTSx8mcFf/d/oK25UB5fEk5+98S5wk1vJHjaOtJuw9ilDQeoNQsz3sh40yjGuOibg9vhZzb90WFNq6uW5Nn5bp7zBTp18vrf2Orcg0kehdTYs9I+m0rEH8TkD17X+IhhdFvds1CoVvT+MxN2ksME8zVrH1AeCT/YGppAw5IPLC8iKc2CRrxF4V9ygnlzHUhczBOLZk+HqsJ+ae2KiX+/PY2R5sRM+etHRK/G7DqMLevbVdninJ96XvTfY0vwyKeXsEUkVMBZm79FKWM+Ps9DB5ge28YLnulfr3a2DRCghUEN/6M7ZjZtRbqNustpLNbUDKCVa2vDC2wphv7zDkVLcaiVC1mkg+4R/NJRl71zZfo2C5IpKhQLiUDVWXRCiu8DipdfpApWH5+YQvw/d5nI0KjQ60wOVPbQCr3CUwvkNrdgtNkWguv+yRO7tTpkxF9o1nBwY2sh6Ui3WvZ9kl0UHmNaJBsqgHXa0q/XGfd5EQUgDu97IrJZnhJB+a75MuG7NqBjzUE1lQ58kwbzLAe3VVY/vFptFddUheuHbz4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
