travis:
  secure:
    BINSTAR_TOKEN: ICIu40V82ZMBUPiJEAvfobviD/KwKn7ny1Qq+SYKQSxEaiBbyxEr4HjHOa3PKypAicuOo+KBRMlX6DMi3i6MboM5L+Ju3C1oK2iXjX0XbBqLBQ942MN6Tw0vIIvoxClDK7mriDp8m8KoJslGJ0fiIgXITKYnS9SJKD7OkFggG+xRM/5QBSbUMLYMPEffhKwlpd2zO58CmJdQUJfniqCqipYGpVLJ3hs2HrSQXWcDOv6/T7hAjyc9qapEZiR/aZ8Lp/a3QW98A59DJetDX6OGFCFbAxRtzG7fmpVL48HIlCEFf7WpU3xNl0zz1ahsZIPQgSgWYXERfyTk3CeNUcoO675WPMsHQMH4gntfhk/KtXcEZJzcrsQ9U9davHuU3n/DIbug51MvoQhZ5kyTMGWfLz1JgqETVcnYfv+hLID7CCANv8KLSmaHzIZKNdqkF5506UBr0KvvIq56llfaz5nKgCbKhrzBRIqA+18TRTt53xqCAqtXfqHw048v5J3t/H/+JkfmyPmiQH3x3kzQYcjqNpw8qIoUO0qOgoT/f38XhLS5pQ1Yak3XBgZ3zh3UU3x413V1zJ+J7RhVmiKRwHvR1owv+VG8UWpT7mKU8hFed65r6TwHCscN+GIp3u7wxtGUsgP/qNXGlHx304ajJQW7AC4p04jDD8F8v2bBBRLY1CM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
